{
 "title": "Global SSH",
 "description": "Global SSH Logs for Loki",
 "tags": [
  "loki",
  "linux",
  "ssh"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   {
    "name": "label_name",
    "label": "Label Name",
    "query": {}
   },
   {
    "name": "label_value",
    "label": "Label Value",
    "query": {}
   },
   {
    "name": "job",
    "label": "Job",
    "query": {}
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Total Failed Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\", syslog_identifier=\"sshd\"} |~\": Failed|: Invalid|: Connection closed by authenticating user\" | __error__=\"\" [$__auto])"
    }
   ]
  },
  {
   "title": "Total Failed Connections - Unique IP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (count by (ip, instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\", syslog_identifier=\"sshd\"} |~\": Invalid|: Connection closed by authenticating user|: Failed\" |~\".* from .*\" | pattern `<_> from <ip> port` | __error__=\"\" [$__auto])) or count by (ip, instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\", syslog_identifier=\"sshd\"} |~\": Invalid|: Connection closed by authenticating user|: Failed\" !~\".* from .*\" | pattern `<_> user <_> <ip> port` | __error__=\"\" [$__auto]))) or on() vector(0)"
    }
   ]
  },
  {
   "title": "Total Failed Connections - Unique Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (count by (username, instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\", syslog_identifier=\"sshd\"} |~\": Invalid|: Connection closed by authenticating user|: Failed .* user\" | pattern `<_> user <username> <_> port` | __error__=\"\" [$__auto])) or count by (username, instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\", syslog_identifier=\"sshd\"} |=\": Failed\" !~\"invalid user\" | pattern `<_> for <username> from <_> port` | __error__=\"\" [$__auto]))) or on() vector(0)"
    }
   ]
  },
  {
   "title": "Total Open Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\", syslog_identifier=\"sshd\"} |=\": session opened for\" | __error__=\"\" [$__auto])) or on() vector(0)"
    }
   ]
  },
  {
   "title": "Total Open Connections - Unique IP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count by (ip, instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\", syslog_identifier=\"sshd\"} |=\": Accepted\" | pattern `<_> Accepted <_> for <_> from <ip> port <_>` | __error__=\"\" [$__auto])) or on() vector(0)"
    }
   ]
  },
  {
   "title": "Total Open Connections - Unique Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (count by (username, instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\", syslog_identifier=\"sshd\"} |=\": session opened for\" | pattern `<_> session opened for user <username>(` | username !~\".* by \" | __error__=\"\" [$__auto])) or count by (username, instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\", syslog_identifier=\"sshd\"} |=\": session opened for\" | pattern `<_> session opened for user <username> <_>` | username !~\".*(uid=.*)\" | __error__=\"\" [$__auto]))) or on() vector(0)"
    }
   ]
  },
  {
   "title": "SSH Log in bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "bytes_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\", syslog_identifier=\"sshd\"} | __error__=\"\" [$__auto])"
    }
   ]
  },
  {
   "title": "Global SSH Stats - Open and Failed Connections",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\", syslog_identifier=\"sshd\"} |~\": Failed|: Invalid|: Connection closed by authenticating user\" | __error__=\"\" [$__auto])) or on() vector(0)"
    },
    {
     "expr": "sum by (instance) (count by (ip, instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\", syslog_identifier=\"sshd\"} |~\": Invalid|: Connection closed by authenticating user|: Failed\" |~\".* from .*\" | pattern `<_> from <ip> port` | __error__=\"\" [$__auto])) or count by (ip, instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\", syslog_identifier=\"sshd\"} |~\": Invalid|: Connection closed by authenticating user|: Failed\" !~\".* from .*\" | pattern `<_> user <_> <ip> port` | __error__=\"\" [$__auto]))) or on() vector(0)"
    },
    {
     "expr": "sum by(instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\", syslog_identifier=\"sshd\"} |=\": session opened for\" | __error__=\"\" [$__auto])) or on() vector(0)"
    },
    {
     "expr": "count by (ip, instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\", syslog_identifier=\"sshd\"} |=\": Accepted\" | pattern `<_> Accepted <_> for <_> from <ip> port <_>` | __error__=\"\" [$__auto])) or on() vector(0)"
    },
    {
     "expr": "sum by (instance) (count by (username, instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\", syslog_identifier=\"sshd\"} |~\": Invalid|: Connection closed by authenticating user|: Failed .* user\" | pattern `<_> user <username> <_> port` | __error__=\"\" [$__auto])) or count by (username, instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\", syslog_identifier=\"sshd\"} |=\": Failed\" !~\"invalid user\" | pattern `<_> for <username> from <_> port` | __error__=\"\" [$__auto]))) or on() vector(0)"
    },
    {
     "expr": "sum by (instance) (count by (username, instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\", syslog_identifier=\"sshd\"} |=\": session opened for\" | pattern `<_> session opened for user <username>(` | username !~\".* by \" | __error__=\"\" [$__auto])) or count by (username, instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\", syslog_identifier=\"sshd\"} |=\": session opened for\" | pattern `<_> session opened for user <username> <_>` | username !~\".*(uid=.*)\" | __error__=\"\" [$__auto]))) or on() vector(0)"
    }
   ]
  },
  {
   "title": "Global SSH Stats - Open vs Failed Connections - Over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\", syslog_identifier=\"sshd\"} |~\": Failed|: Invalid|: Connection closed by authenticating user\" | __error__=\"\" [$__auto]))",
     "legendFormat": "Failed - {{ instance }}"
    },
    {
     "expr": "sum by(instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\", syslog_identifier=\"sshd\"} |=\": session opened for\" | __error__=\"\" [$__auto]))",
     "legendFormat": "Open - {{ instance }}"
    }
   ]
  }
 ]
}