# https://samber.github.io/awesome-prometheus-alerts/rules#blackbox
groups:
  - name: blackbox_http
    rules:
      - alert: BlackboxHttpProbeFailure
        expr: "probe_http_status_code <= 199 OR probe_http_status_code >= 400"
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "HTTP probe failure"
          description: "HTTP status code is not 200-399\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: BlackboxHttpProbeHighLatency
        expr: "avg_over_time(probe_http_duration_seconds[1m]) > 1"
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "HTTP probe high latency"
          description: "HTTP probe took more than 1s\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: BlackboxSslCertificateWillExpireSoon
        expr: "0 <= round((last_over_time(probe_ssl_earliest_cert_expiry[10m]) - time()) / 86400, 0.1) < 7"
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "SSL certificate will expire in less than 7 days"
          description: "SSL certificate expires in less than 7 days\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: BlackboxSslCertificateWillExpireTomorrow
        expr: "0 <= round((last_over_time(probe_ssl_earliest_cert_expiry[10m]) - time()) / 86400, 0.1) < 1"
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: "SSL certificate will expire tomorrow"
          description: "SSL certificate expires in less than 1 day\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: BlackboxSslCertificateExpired
        expr: "round((last_over_time(probe_ssl_earliest_cert_expiry[10m]) - time()) / 86400, 0.1) < 0"
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: "SSL certificate expired"
          description: "SSL certificate has expired already\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: BlackboxSslCertificateChanged
        expr: "changes(probe_ssl_last_chain_info[5m]) != 0"
        for: 5m
        labels:
          severity: info
        annotations:
          summary: "SSL certificate metadata value changed"
          description: "The metric value 'probe_ssl_last_chain_info' has changed in the 5m\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: BlackboxConfigurationReloadFailure
        expr: blackbox_exporter_config_last_reload_successful != 1
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: Blackbox configuration reload failure (instance {{ $labels.instance }})
          description: "Blackbox configuration reload failure\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
