{
 "title": "healthcheck [HTTP]",
 "tags": [
  "blackbox",
  "http"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(up{job=~\"$job\"},env)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(up{job=~\"$job\", env=~\"$env\"},service)"
    }
   },
   {
    "name": "targets",
    "label": "Targets",
    "query": {
     "query": "label_values(up{job=~\"$job\", env=~\"$env\", service=~\"$service\"},instance)"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Check time for $service targets",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{service=~\"$service\", job=~\"$job\"}",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"value\", probe_http_status_code{service=~\"$service\", job=~\"$job\"})",
     "legendFormat": "HTTP {{ value }}"
    }
   ]
  },
  {
   "title": "HTTPS stages for $service services",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{service=~\"$service\", job=~\"$job\"}",
     "legendFormat": "{{service}} {{phase}}"
    }
   ]
  },
  {
   "title": " ",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$targets\", job=~\"$job\"} - 0"
    },
    {
     "expr": "probe_http_status_code{instance=~\"$targets\", job=~\"$job\"} - 0"
    },
    {
     "expr": "probe_http_ssl{instance=~\"$targets\", job=~\"$job\"} - 0"
    },
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$targets\", job=~\"$job\"} - time()"
    },
    {
     "expr": "avg_over_time(probe_success{instance=~\"$targets\", job=~\"$job\"}[$__range]) * 100"
    }
   ]
  }
 ]
}